name: UI testing

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Create .env file from GitHub Secrets
        run: |
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "HEADLESS=${{ secrets.HEADLESS }}" >> .env
          echo "BROWSERS=${{ secrets.BROWSERS }}" >> .env
          echo "TEST_USER__EMAIL=${{ secrets.TEST_USER__EMAIL }}" >> .env
          echo "TEST_USER__USERNAME=${{ secrets.TEST_USER__USERNAME }}" >> .env
          echo "TEST_USER__PASSWORD=${{ secrets.TEST_USER__PASSWORD }}" >> .env

      - name: Run Playwright tests with pytest and generate allure
        run: |
          pytest -m regression --alluredir=./allure-results

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh_pages
          PUBLISH_DIR: allure-history
