name: UI testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Which tests to run"
        required: true
        default: all_tests
        type: choice
        options:
          - all_tests
          - smoke_tests

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Create .env file from GitHub Secrets
        run: |
          echo "APP_URL=${{ secrets.APP_URL }}" > .env
          echo "HEADLESS=${{ secrets.HEADLESS }}" >> .env
          echo 'BROWSERS=${{ secrets.BROWSERS }}' >> .env
          echo "TEST_USER.EMAIL=${{ secrets.TEST_USER_EMAIL }}" >> .env
          echo "TEST_USER.USERNAME=${{ secrets.TEST_USER_USERNAME }}" >> .env
          echo "TEST_USER.PASSWORD=${{ secrets.TEST_USER_PASSWORD }}" >> .env

      - name: Run all tests
        if: ${{ github.event.inputs.deployment_target == 'all_tests' || github.event_name == 'pull_request' }}
        run: pytest --tracing=retain-on-failure --alluredir=allure-results

      - name: Run smoke tests
        if: ${{ github.event.inputs.deployment_target == 'smoke_tests' }}
        run: pytest -m smoke --tracing=retain-on-failure --alluredir=allure-results

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
